_target_: src.models.deepjscc_module.DeepJSCCModule

num_devices: 2
N: 256
M: 16

loss: sum_mse

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

net:
  _target_: src.models.nets.standard.StandardNet
  num_devices: ${model.num_devices}
  M: ${model.M}
  encoder:
    _target_: src.models.components.deepjsccq2.DeepJSCCQ2Encoder
    _partial_: true
    N: ${model.N}
    M: ${model.M}
  decoder:
    _target_: src.models.components.deepjsccq2.DeepJSCCQ2Decoder
    _partial_: true
    N: ${model.N}
    M: ${model.M}
  channel:
    _target_: src.models.components.channels.ComplexAWGNMAC
  power_constraint:
    _target_: src.models.components.power_constraints.ComplexAveragePowerConstraint
    power: 1
    num_devices: ${model.num_devices}
