_target_: src.datamodules.cifar10_datamodule.CIFAR10DataModule
data_dir: ${paths.data_dir}
batch_size: 64
train_val_split: [45000, 5000]
num_workers: 16
pin_memory: True
num_train_samples: 0
num_val_samples: 0
num_test_samples: 0
regroup_every_training_epoch: 1
group_size: ${model.num_devices}
min_snr: 0.0
max_snr: 20.0
